// MCRPEventListener.java

package usr.interactor;

import java.util.EventListener;

/**
 * An MCRPEventListener is a tagging interface for listeners 
 * of MCRPEvents.
 * Java says that all event listener interfaces must extend
 * EventListener.
 */
public interface MCRPEventListener extends EventListener {
    /**
     * This is the callback for an MCRPEventListener.
     * This method, ssipEvent(), will be called when
     * there is an MCRP event.
     * @param event the event generated by the server.
     */
    public void ssipEvent(MCRPEvent event);
}
