#!/bin/sh

# remove file if it is there
#echo "Removing file $1.txt, if it is there"
rm $1.txt 2> /dev/null
awk 'BEGIN { FS = "\t" } {a1[FNR-1]+=$2;a2[FNR-1]+=$3;a3[FNR-1]+=$4;a4[FNR-1]+=$5;a5[FNR-1]+=$6;a6[FNR-1]+=$7;a7[FNR-1]=$8;a8[FNR-1]+=$9;a9[FNR-1]+=$10;a10[FNR-1]+=$11;a11[FNR-1]+=$12;a12[FNR-1]+=$13;a13[FNR-1]+=$14;a14[FNR-1]+=$15;a15[FNR-1]+=$16;a16[FNR-1]+=$17;a17[FNR-1]+=$18;a18[FNR-1]+=$19;a19[FNR-1]+=$20;a20[FNR-1]+=$21;a21[FNR-1]+=$22;a22[FNR-1]+=$23;a23[FNR-1]+=$24;a24[FNR-1]+=$25;a25[FNR-1]+=$26;a26[FNR-1]+=$27;a27[FNR-1]+=$28;a28[FNR-1]+=$29;a29[FNR-1]+=$30;a30[FNR-1]+=$31;c[FNR-1]++;}END{for(i=0;i<FNR;i++){gsub(/ /,"_",a7[i]);print i,a1[i]/c[i],a2[i]/c[i],a3[i]/c[i],a4[i]/c[i],a5[i]/c[i],a6[i]/c[i],a7[i],a8[i]/c[i],a9[i]/c[i],a10[i]/c[i],a11[i]/c[i],a12[i]/c[i],a13[i]/c[i],a14[i]/c[i],a15[i]/c[i],a16[i]/c[i],a17[i]/c[i],a18[i]/c[i],a19[i]/c[i],a20[i]/c[i],a21[i]/c[i],a22[i]/c[i],a23[i]/c[i],a24[i]/c[i],a25[i]/c[i],a26[i]/c[i],a27[i]/c[i],a28[i]/c[i],a29[i]/c[i],a30[i]/c[i];}}' $1.* > $1.txt
