#!/bin/sh
echo "impact-of-flows" > scenario
echo "5 10 20 30" > range
echo "Flows" > rangetype
echo "/Users/lmamatas/Desktop/TNSM-2016-revision-2/images/scenario1/impact-of-flows/" > targetfolder
./plotcpuload cpuload-pullfromentities-100 
./plotmemorystorage memorystorage-pullfromentities-100 
./plotresponsetime responsetime-direct-100 
./plotresponsetime responsetime-pubsub-100
./plotresponsetime responsetime-pullfromentities-100 
./plotresponsetime responsetime-pullfromstorage-100 
cp `cat scenario`/*.pdf `cat targetfolder`

echo "ScenarioGoals-100-10" > scenario
echo "Pull_From_Entity Pull_From_Storage Pub_/_Sub Direct_Communication" > range
echo "" > rangetype
echo "/Users/lmamatas/Desktop/TNSM-2016-revision-2/images/scenario1/impact-of-method/" > targetfolder
./plotcpuload cpuload-method-100-10
./plotmemorystorage memorystorage-method-100-10
cp `cat scenario`/*.pdf `cat targetfolder`

echo "ScenarioGoals-30-3" > scenario
./plotcpuload cpuload-method-30-3
./plotfreshness freshness-method-30-3
./plotmemorystorage memorystorage-method-30-3
./plotresponsetime responsetime-method-30-3
cp `cat scenario`/*.pdf `cat targetfolder`

echo "Scenario2" > scenario
echo "1 2 3 4 5" > range
echo "Flows" > rangetype
echo "/Users/lmamatas/Desktop/TNSM-2016-revision-2/images/scenario2/" > targetfolder
./plotcpuload cpuload-pullfromentitygov-30
./plotfreshness freshness-pullfromentitygov-30
./plotfreshness freshness-pullfromstoragegov-30
./plotmemorystorage memorystorage-pullfromentitygov-30
./plotresponsetime responsetime-pullfromentitygov-30
./plotresponsetime responsetime-pullfromstoragegov-30
echo "1+1 1+2 1+3 1+4" > range
./plotresponsetime responsetime-diverseflowsdirecttopullfromstoragegov-30
./plotresponsetimemonitoredflows responsetimemonitoredflows-diverseflowsdirecttopullfromstoragegov-30
cp `cat scenario`/*.pdf `cat targetfolder`

echo "Scenario3/scalability" > scenario
echo "50 100 200 300 400 500" > range
echo "Routers" > rangetype
echo "/Users/lmamatas/Desktop/TNSM-2016-revision-2/images/scenario3/scalability/" > targetfolder
./plotcpuload cpuload-scalability-direct-10
./plotmemorystorage memorystorage-scalability-direct-10
./plotresponsetime responsetime-scalability-direct-10

echo "1 2 5 10" > range
echo "Flows" > rangetype
./plotcpuload cpuload-scalability-pullfromstoragegov-300
./plotmemorystorage memorystorage-scalability-pullfromstoragegov-300
./plotresponsetime responsetime-scalability-pullfromstoragegov-300

cp `cat scenario`/*.pdf `cat targetfolder`

