#!/bin/sh
echo "Creating maxenergy figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="maxenergy"
    # create file  
    ./maxenergy > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Maximum_Energy_Consumed Time Maximum_Energy_Consumed"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plotmaxenergyfigure $result

./createpicture `cat scenario`/$filename
