#!/bin/sh
echo "Creating averagenetworkutilization figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="averagenetworkutilization"
    # create file  
    ./averagenetworkutilization > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Average_Network_Utilization Time Average_Network_Utilization"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plotaveragenetworkutilizationfigure $result

./createpicture `cat scenario`/$filename
