#!/bin/sh
echo "Creating maxmemoryallocation figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="maxmemoryallocation"
    # create file  
    ./maxmemoryallocation > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Maximum_Memory_Allocation Time Maximum_Memory_Allocation"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plotmaxmemoryallocationfigure $result

./createpicture `cat scenario`/$filename
