#!/bin/sh
echo "Creating averagecpuload figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="averagecpuload"
    # create file  
    ./averagecpuload > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Average_CPU_Load Time Average_CPU_Load"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plotaveragecpuloadfigure $result

./createpicture `cat scenario`/$filename
