#!/bin/sh
echo "Creating minenergy figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="minenergy"
    # create file  
    ./minenergy > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Minimum_Energy_Consumed Time Minimum_Energy_Consumed"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plotminenergyfigure $result

./createpicture `cat scenario`/$filename
