#!/bin/sh
echo "Creating averageoutgoingthroughput figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="averageoutgoingthroughput"
    # create file  
    ./averageoutgoingthroughput > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Average_Outgoing_Throughput Time Average_Outgoing_Throughput"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plotaverageoutgoingthroughputfigure $result

./createpicture `cat scenario`/$filename
