#!/bin/sh
echo "Creating response time figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="responsetime"
    # create file  
    ./responsetime > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Average_Response_Time Time Response_Time"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plotresponsetimefigure $result

./createpicture `cat scenario`/$filename
