#!/bin/sh
echo "Creating memory storage figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="memorystorage"
    # create file  
    ./memorystorage > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Memory_State Time Memory_State"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plotmemorystoragefigure $result

./createpicture `cat scenario`/$filename
