#!/bin/sh

echo "Creating averageenergy figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="averageenergy"
    # create file  
    ./averageenergy > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Average_Energy_Consumed Time Average_Energy_Consumed"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plotaverageenergyfigure $result

./createpicture `cat scenario`/$filename
