#!/bin/sh
echo "Creating freshness figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="freshness"
    # create file  
    ./freshness > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Average_Information_Freshness Time Information_Freshness"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plotfreshnessfigure $result

./createpicture `cat scenario`/$filename
