#!/bin/sh
echo "Creating totalenergy figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="totalenergy"
    # create file  
    ./totalenergy > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Total_Energy_Consumed Time Total_Energy_Consumed"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plottotalenergyfigure $result

./createpicture `cat scenario`/$filename
