#!/bin/sh
echo "Creating minoutgoingthroughput figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="minoutgoingthroughput"
    # create file  
    ./minoutgoingthroughput > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Minimum_Outgoing_Throughput Time Minimum_Outgoing_Throughput"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plotminoutgoingthroughputfigure $result

./createpicture `cat scenario`/$filename
