#!/bin/sh
echo "Creating minnetworkutilization figure"

if [[ $# -eq 0 ]] ; then
    echo 'No parameters passed, using default filename.'
    filename="minnetworkutilization"
    # create file  
    ./minnetworkutilization > `cat scenario`/$filename.txt
else
    filename=$1
fi

counter=2
result="`cat scenario`/$filename.txt Minimum_Network_Utilization Time Minimum_Network_Utilization"

for a in `cat range`
do
        rangetype="`cat rangetype`_${a}"
        result="${result} ${rangetype} $counter"
        let counter+=1
done

echo $result

./plotminnetworkutilizationfigure $result

./createpicture `cat scenario`/$filename
