#!/bin/sh
echo "set style line 1 lt 1 lw 5 lc rgb 'black'" >> plot.p
echo "set style line 2 lt 1 lw 5 lc rgb 'gray'" >> plot.p
echo "set style line 3 lt 1 lw 5 lc rgb 'red'" >> plot.p
echo "set style line 4 lt 1 lw 5 lc rgb 'blue'" >> plot.p
echo "set style line 5 lt 1 lw 5 lc rgb 'yellow'" >> plot.p
echo "set style line 6 lt 1 lw 5 lc rgb 'green'" >> plot.p
echo "set style line 7 lt 3 lw 3 lc rgb 'black'" >> plot.p
echo "set style line 8 lt 6 lw 3 lc rgb 'black'" >> plot.p
echo "set style line 9 lt 1 lw 3 lc rgb 'black'" >> plot.p
echo "set style line 10 lt 2 lw 5 lc rgb 'black'" >> plot.p
echo "set style line 11 lt 3 lw 5 lc rgb 'black'" >> plot.p
echo "set style line 12 lt 6 lw 5 lc rgb 'black'" >> plot.p
echo "set style line 13 lt 2 lw 3 lc rgb 'black'" >> plot.p
