#!/bin/bash
#ps ax | grep LocalController | awk '{print $1}' | xargs kill
for h in clayone claytwo claythree clayfour claydesk1 claydesk2 ethane methane butane propane pentane; do echo "Checking heap sizes in $h"; ssh $h "java -XX:+PrintFlagsFinal -version | grep HeapSize" 2> /dev/null; done
