#!/bin/bash

#ps ax | grep LocalController | awk '{print $1}' | xargs kill
for h in `cat machines`; do echo "Killing localcontroller in $h"; ssh $h "ps ax | grep -e 'lmamatas.*LocalController' | grep -v grep | awk '{print \$1}' | xargs kill -9"; done
