#!/bin/bash

#ps ax | grep Router | grep -v grep | awk '{print $1}' | xargs kill -9
for h in `cat machines`; do echo "Killing routers in $h"; ssh $h "ps ax | grep -e 'lmamatas.*Router' | grep -v grep | awk '{print \$1}' | xargs kill -9"; done
